"""WorldModelPlanner — generates candidates, simulates, and selects the best action."""

from __future__ import annotations

import logging
from typing import Any, Dict, List, Optional

from PIL import Image

from agentic_integrator.world_model.base import (
    PlanningResult,
    SimulationResult,
    WorldModel,
)
from agentic_integrator.world_model.safety_gate import SafetyGate
from agentic_integrator.memory.prediction_memory import PredictionMemory

logger = logging.getLogger("agentic_integrator.planner")


class WorldModelPlanner:
    """
    Plans actions using the world model.

    Flow:
    1. Receive N candidate actions from the enhanced worker
    2. Check adaptive confidence — skip simulation if high confidence
    3. Simulate each candidate via the world model
    4. Run safety gate on each simulation
    5. Rank by composite score
    6. Return the best action with full planning context
    """

    def __init__(
        self,
        world_model: WorldModel,
        safety_gate: SafetyGate,
        prediction_memory: PredictionMemory,
        num_candidates: int = 3,
        adaptive_confidence: bool = True,
        high_confidence_threshold: float = 0.85,
        min_candidates_for_simulation: int = 2,
    ):
        self.world_model = world_model
        self.safety_gate = safety_gate
        self.prediction_memory = prediction_memory
        self.num_candidates = num_candidates
        self.adaptive_confidence = adaptive_confidence
        self.high_confidence_threshold = high_confidence_threshold
        self.min_candidates_for_simulation = min_candidates_for_simulation

        # Stats
        self._total_plans = 0
        self._plans_skipped = 0
        self._safety_blocks = 0

    def plan(
        self,
        screenshot: Image.Image,
        candidates: List[str],
        task_description: str,
        action_history: List[str],
        worker_confidence: float = 0.5,
        context: Optional[Dict[str, Any]] = None,
    ) -> PlanningResult:
        """
        Select the best action from candidates using world model simulation.

        Args:
            screenshot: Current screen state
            candidates: List of candidate actions generated by the worker
            task_description: The overall task
            action_history: Previously executed actions
            worker_confidence: The worker's own confidence in its top choice
            context: Additional context

        Returns:
            PlanningResult with the selected action and all simulations
        """
        self._total_plans += 1

        if not candidates:
            raise ValueError("No candidate actions provided")

        # Single candidate — no need to simulate
        if len(candidates) == 1:
            sim = self.world_model.simulate(
                screenshot, candidates[0], task_description, action_history, context
            )
            return PlanningResult(
                selected_action=candidates[0],
                selected_simulation=sim,
                all_simulations=[sim],
            )

        # Adaptive confidence: skip simulation for high-confidence simple actions
        if self.adaptive_confidence and worker_confidence > self.high_confidence_threshold:
            action_type = self._classify_action(candidates[0])
            if action_type in ("simple_nav", "typing", "scrolling"):
                self._plans_skipped += 1
                # Return top candidate without simulation
                dummy_sim = SimulationResult(
                    action=candidates[0],
                    predicted_state_description="Skipped (high confidence)",
                    task_progress_score=worker_confidence,
                    confidence=worker_confidence,
                    safety_score=1.0,
                    reasoning=f"Adaptive skip: {action_type} with confidence {worker_confidence:.2f}",
                )
                return PlanningResult(
                    selected_action=candidates[0],
                    selected_simulation=dummy_sim,
                    all_simulations=[dummy_sim],
                    planning_skipped=True,
                    skip_reason=f"High confidence ({worker_confidence:.2f}) on {action_type}",
                )

        # Simulate all candidates
        simulations = self.world_model.batch_simulate(
            screenshot, candidates, task_description, action_history, context
        )

        # Run safety gate
        for sim in simulations:
            safety_result = self.safety_gate.check(sim)
            if safety_result.blocked:
                sim.safety_score = 0.0
                sim.risk_description = safety_result.reason
                self._safety_blocks += 1
                logger.warning(f"Safety gate blocked: {sim.action[:50]}... — {safety_result.reason}")

        # Rank by composite score
        ranked = sorted(simulations, key=lambda s: s.composite_score, reverse=True)

        best = ranked[0]
        logger.info(
            f"Planner selected action (score={best.composite_score:.3f}): "
            f"{best.action[:80]}..."
        )

        return PlanningResult(
            selected_action=best.action,
            selected_simulation=best,
            all_simulations=ranked,
        )

    def _classify_action(self, action: str) -> str:
        """Classify an action type for adaptive confidence."""
        action_lower = action.lower()

        if any(kw in action_lower for kw in ("click", "moveto")):
            # Check if it's a simple navigation click
            if any(kw in action_lower for kw in ("delete", "submit", "send", "remove", "purchase")):
                return "dangerous_click"
            return "simple_nav"

        if "typewrite" in action_lower or "write(" in action_lower:
            return "typing"

        if "scroll" in action_lower:
            return "scrolling"

        if "hotkey" in action_lower or "press(" in action_lower:
            return "keyboard_shortcut"

        return "complex"

    def get_stats(self) -> Dict[str, Any]:
        return {
            "total_plans": self._total_plans,
            "plans_skipped": self._plans_skipped,
            "safety_blocks": self._safety_blocks,
            "skip_rate": self._plans_skipped / max(self._total_plans, 1),
        }
